# Generated by Django 5.0.6 on 2024-07-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicioapp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='Name',
        ),
    ]
