# Generated by Django 5.0.6 on 2024-07-09 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicioapp', '0005_rename_name_appointment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Name',
            new_name='name',
        ),
    ]
